### ISSUE TITLE
Run Report not fully rendering when phone screen is off

### ISSUE THREAD

**Issue by qreoct** [qreoct/runstarter#16]
# Summary:
Run Report details not fully rendering when phone screen is off
## Steps to reproduce:
1. Start a game
2. Turn off phone screen/multitask
3. Complete the run
4. Run Report map shows up, but run details (e.g. pace, distance) do not
## Expected behavior:
Run details should show up on run report
## Additional notes:
Tested with apk on phone

**Comment by kleonang** [comment]
Might be a dark mode issue:
- After starting run, enable dark mode
- When run report loaded, it'll run the dark mode state (all text white, blends into white background) and appears to be blank
